config/routes.rb
Miradaanimal::Application.routes.draw do
  resources :raffles

  resources :dogs

  resources :members

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'operativo' => 'members#volunteer', :as => :volunteer
  match 'padrinos' => 'members#padrinos', :as => :padrinos
  post 'create_padrino' => 'members#create_padrino', :as => :create_padrino
  match 'miembro' => 'members#new_member', :as => :member
  match 'create_member' => 'members#create_member', :as => :member
  match 'check' => 'members#check', :as => :check
  match 'thank_you' => 'members#thank_you', :as => :thank_you
  match 'rifa' => 'raffles#new', :as => :rifa
  match 'donaciones' => 'donations#new_donation'
  match 'cdonaciones' => 'donations#create'
  match 'thank_you_donation' => 'donations#thank_you_donation', :as => :thank_you_donation
  match 'waitlist' => 'dogs#waitlist'
  match 'waitlistview' => 'dogs#waitlistview'
  
  match 'toggle_verified' => 'raffles#toggle_verified', :as => :toggle_verified

 root :to => 'dogs#welcome'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  attr_accessible :arrival_date, :comments, :date_of_birth, :gender, :adopted, :name, :size, :sterilized, :story, :photo1, :photo2, :photo3, :photo4
  has_attached_file :photo1, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo1, :content_type => /\Aimage\/.*\Z/
    has_attached_file :photo2, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo2, :content_type => /\Aimage\/.*\Z/
    has_attached_file :photo3, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo3, :content_type => /\Aimage\/.*\Z/
    has_attached_file :photo4, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo4, :content_type => /\Aimage\/.*\Z/


  scope :adoptados, where("adopted" => true)
  scope :por_adoptar, where("adopted" => false)

  belongs_to :member
end

app/controllers/dogs_controller.rb
class DogsController < InheritedResources::Base
  def welcome
  	@dogs = Dog.where(:adopted => [nil, false]).limit(15)
  end

  #returns the dogs that are not adopted, aka waiting in the shelter to be adopted
  def waitlist

  	@dogs = Dog.where(:adopted => [nil, false]).limit(25)

  	respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @dogs }
    end
  end

  def waitlistview

  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog, :html => { :multipart => true }) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <%= f.file_field :photo1 %>
  <%= f.file_field :photo2 %>
  <%= f.file_field :photo3 %>
  <%= f.file_field :photo4 %>
  <div class="field">
    <%= f.label :arrival_date %><br />
    <%= f.datetime_select :arrival_date %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, [["Hembra", 'Hembra'],["Macho", 'Macho']], {}, :class => "form-control input-normal" %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.select :size, [["Pequeño", 'Pequeño'],["Mediano", 'Mediano'],["Grande", 'Grande']], {}, :class => "form-control input-normal" %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.datetime_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :sterilized %><br />
    <%= f.check_box :sterilized %> Esterilizado
  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_area :story, :rows => 8 %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :rows => 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/new.html.erb
<h1><%= t(:new_dog)%></h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dog.name %>
</p><% if @dog.photo1.exists? %>
<%= image_tag @dog.photo1.url(:medium) %>
<% end %>
<% if @dog.photo2.exists? %>
<%= image_tag @dog.photo2.url(:medium) %>
<% end %>
<p>
  <b>Arrival date:</b>
  <%= @dog.arrival_date %>
</p>

<p>
  <b>Gender:</b>
  <%= @dog.gender %>
</p>

<p>
  <b>Size:</b>
  <%= @dog.size %>
</p>

<p>
  <b>Dateofbirth:</b>
  <%= @dog.date_of_birth %>
</p>

<p>
  <b>Sterilized:</b>
  <%= @dog.sterilized %>
</p>

<p>
  <b>Story:</b>
  <%= @dog.story %>
</p>

<p>
  <b>Comments:</b>
  <%= @dog.comments %>
</p>


<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/waitlist.json.erb
{"dogs":[
 <%= raw @dogs.map{|dog| '{"name":"' +"#{dog.name}" +'","gender":"' + "#{dog.gender}"+'","size":"' + "#{dog.size}"+'","photo":"' + "#{dog.photo1.exists? ? dog.photo1.url(:original).split("?")[0].split("%")[0] : ""}"+'","id":"' + "#{dog.id}" + '"}' }.join(",") %>
]}

app/views/dogs/waitlistview.html.erb
<script type="text/javascript">jQuery(function($){
 $("#prueba").html("HOLA MUNDO!");
}); 

$.getJSON( "http://localhost:3000/waitlist.json", function( data ) {
	console.log(data["dogs"]);
  var items = [];
  $.each( data["dogs"], function( key, val ) {
  	console.log("key: " + key);
  	items.push( 
  		"<div class='vc_col-sm-2 wpb_column vc_column_container'>"+
			"<div class='wpb_wrapper'>"+
				"<div class='wpb_single_image wpb_content_element vc_custom_1438106996103 vc_align_left'>"+
					"<div>"+
						"<div class='wpb_wrapper'>"+
							"<img class='vc_box_border_grey ' src='" +val["photo"] + "' width='200' height='200' alt='"+val["name"]+"' />"+
						"</div>"+ 
					"</div>"+
				"</div> "+
			"</div> "+
		"</div> "+
	"<div class='vc_col-sm-2 wpb_column vc_column_container'>"+
		"<div class='wpb_wrapper'>"+
			"<div class='wpb_text_column wpb_content_element  vc_custom_1438108098206'>"+
				"<div class='wpb_wrapper'>"+
			  		"<p id='" + key + "' style='text-align: left;'> Nombre: " + val["name"] + "</p>" +
			  		"<p id='" + key + "' style='text-align: left;'> Sexo: " + val["gender"] + "</p>" +
			  		"<p id='" + key + "' style='text-align: left;'> Tamaño: " + val["size"] + "</p>" +
			  	"</div> "+
	"</div> <a href='' target='_self' class='qbutton normal_button small qbutton_with_icon' style='' ><i class='fa fa-heart' style='color: #dd3333;'></i><span>adopta</span></a>"+
		"</div> "+
	"</div> ");
  });
 
  $( "<div/>", {
    "class": "my-new-list",
    html: items.join( "" )
  }).appendTo( "body" );
});

</script>


<div id="prueba">
chao
</div>

app/views/dogs/welcome.html.erb
<% @dogs.each do |dog| %>
	<% if dog.photo1.exists? %>
		<%= image_tag dog.photo1.url(:medium) %>
	<% end %>
<% end %>