config/routes.rb
Miradaanimal::Application.routes.draw do
  resources :raffles

  resources :dogs

  resources :members

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'operativo' => 'members#volunteer', :as => :volunteer
  match 'padrinos' => 'members#padrinos', :as => :padrinos
  post 'create_padrino' => 'members#create_padrino', :as => :create_padrino
  match 'miembro' => 'members#new_member', :as => :member
  match 'create_member' => 'members#create_member', :as => :member
  match 'check' => 'members#check', :as => :check
  match 'thank_you' => 'members#thank_you', :as => :thank_you
  match 'rifa' => 'raffles#new', :as => :rifa
  match 'donaciones' => 'donations#new_donation'
  match 'cdonaciones' => 'donations#create'
  match 'thank_you_donation' => 'donations#thank_you_donation', :as => :thank_you_donation
  match 'waitlist' => 'dogs#waitlist'
  match 'waitlistview' => 'dogs#waitlistview'
  
  match 'toggle_verified' => 'raffles#toggle_verified', :as => :toggle_verified

 root :to => 'dogs#welcome'

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :car, :email, :frequent_donor, :name, :occupation, :phone, :rut, :volunteer, :emergency_contact_name, :emergency_contact_phone, :health, :donor_amount

  has_many :registrations
  has_many :donations
  has_many :dogs

  validates :email, :presence => true,
                    :uniqueness => true

  scope :voluntarios_domingo, joins(:registrations).where("registrations.day" => DateTime.now.end_of_week.at_midnight) 
  scope :donante_frecuente, where(:frequent_donor => true)
  scope :padrinos, joins(:dogs).where("dogs.member_id IS NOT NULL" )

  def norm_rut
  	if !self.rut.nil?
	  	rut = self.rut.tr('.-','')
	  	rut = rut[0..rut.length-2] + "-"+rut[rut.length-1]
	  	rut = rut[0..rut.length-9] + "." + rut[rut.length-8..rut.length-6] + "." + rut[rut.length-5..rut.length] 
	  	self.rut = rut
	  end
  end

end

app/controllers/members_controller.rb
#encoding: utf-8
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  def new_member
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])
    @member.norm_rut

    respond_to do |format|
      if @member.save
        registration = Registration.where(:member_id => @member.id, :day => DateTime.now.end_of_week.at_midnight)
        if registration.count == 0
          Registration.create(:member_id => @member.id, :day => DateTime.now.end_of_week.at_midnight)
        end
        AdminMailer.thanks_volunteer(@member).deliver
        format.html { redirect_to thank_you_path(:notice => "¡Gracias! Registro exitoso") }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

   # POST /members
  # POST /members.json
  def create_member
    @member = Member.new(params[:member])
    puts "bla " + @member.name.to_s
    @member.norm_rut
    if @member.donor_amount != ""
      @member.frequent_donor = true
    end

    respond_to do |format|
      if @member.save
        format.html { redirect_to thank_you_path(:notice => "¡Gracias! Registro exitoso") }
      else
        format.html { render action: "new_member" }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])
    @member.norm_rut
    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

	def volunteer

	end

	def check
		m = Member.where(:email => params[:email]).first
		if m
      m.car = params[:car]
      m.save
      registration = Registration.where(:member_id => m.id, :day => DateTime.now.end_of_week.at_midnight).first
      if registration.nil?
  			Registration.create(:member_id => m.id, :day => DateTime.now.end_of_week.at_midnight)
        AdminMailer.thanks_volunteer(m).deliver
        redirect_to thank_you_path(:notice => "¡Gracias! Registro exitoso")
      else
        redirect_to thank_you_path(:notice => "Ya estabas inscrito para este operativo")
      end
      return
			
		else
			@member = Member.new
			@member.email = params[:email]
      @member.car = params[:car]
			render new_member_path
		end
	end

	def thank_you
		@notice = params[:notice]
	end

  def padrinos
    @dogs = Dog.where(:member_id => nil, :adopted => [false, nil])
  end

  def create_padrino
    dog = Dog.find(params[:dog])
    mem = Member.find_by_email(params[:member][:email])
    if !mem.nil?
      dog.member_id = mem.id
      dog.save
    else
      redirect_to padrinos_path(:notice => "Tu mail no está registrado, inscríbete como miembro primero")
      return
    end

    redirect_to thank_you_path(:notice => "¡#{dog.name} estará feliz de saber que tiene un nuevo padrino!")
    return
  end
  
end

app/helpers/members_helper.rb
module MembersHelper


	
end

app/views/members/_form.html.erb
<%= form_for(@member)do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :name, %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :rut %><br />
    <%= f.text_field :rut %>
  </div>
  <div class="field">
    <%= f.label :volunteer %><br />
    <%= f.check_box :volunteer %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :auto %><br />
    <%= f.check_box :car %>
  </div>
  <div class="field">
    <%= f.label :ocupacion %><br />
    <%= f.text_field :occupation %>
  </div>
  <!--div class="field">
    <%= f.label :frequent_donor %><br />
    <%= f.text_field :frequent_donor %>
  </div-->
  <div class="actions">
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/members/_form_member.html.erb
<%= form_for(@member, url: {action: "create_member"}, :html => {:id => 'form'} ) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>Tuvimos un error:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-8 col-md-offset-2">
  <div class="field">
    <%= f.label :nombre %><font color="red">*</font><br />
    <%= f.text_field :name,  :required=>"true",  :class=>"form-control required" %>
  </div>
  <div class="field">
    <%= f.label :email %><font color="red">*</font><br />
    <%= f.text_field :email,  :required=>"true",  :class=>"form-control required", :type => "email"  %>
  </div>
  <div class="field">
    <%= f.label :rut %><font color="red">*</font><br />
    <%= f.text_field :rut,  :required=>"true",  :class=>"form-control required" %>
  </div>

  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :phone,  :class=>"form-control" %>
  </div>
  <br/>
   <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation,  :class=>"form-control" %>
  </div>
  <br/>
  <div class="field">
    <%= f.label "Si deseas donar un monto mensual ingresalo aquí por favor, no hay mínimos ni máximos" %><br/>
    <%= f.text_field :donor_amount,  :class=>"form-control"  %>
  </div>
  <br/>
  <div class="actions text-center">
    <%= f.submit 'Enviar',  :class=>"btn btn-primary " %><br/><br/>
  </div>
  </div>
<% end %>

app/views/members/_volunteer.html.erb
<%= form_for(@member, :html => {:id => 'form'} ) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>Tuvimos un error:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-8 col-md-offset-2">
  <div class="field">
    <%= f.label :nombre %><font color="red">*</font><br />
    <%= f.text_field :name,  :required=>"true",  :class=>"form-control required" %>
  </div>
  <div class="field">
    <%= f.label :email %><font color="red">*</font><br />
    <%= f.text_field :email,  :required=>"true",  :class=>"form-control required", :type => "email"  %>
  </div>
  <div class="field">
    <%= f.label :rut %><font color="red">*</font><br />
    <%= f.text_field :rut,  :required=>"true",  :class=>"form-control required" %>
  </div>
  <div class="field">
    
    <%= f.check_box :volunteer, {:checked=>true, :hidden => true},  :class=>"form-control" %> 
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :phone,  :class=>"form-control" %>
  </div>
  <div class="field"><br/>
    <%= f.check_box :car %> <%= f.label "Cuentas con un auto para el operativo" %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation,  :class=>"form-control" %>
  </div>
  <br/>
  IMPORTANTE EN CASO DE EMERGENCIA CONTACTAR A:
  <div class="field">
    <%= f.label :emergency_contact_name %><font color="red">*</font><br />
    <%= f.text_field :emergency_contact_name,  :class=>"form-control required" %>
  </div>
  <div class="field">
    <%= f.label :emergency_contact_phone %><font color="red">*</font><br />
    <%= f.text_field :emergency_contact_phone,  :class=>"form-control required" %>
  </div>
  <div class="field">
    <%= f.label "Tienes algún problema de salud o alergia:" %><br />
    <%= f.text_field :health,  :class=>"form-control" %>
  </div>
  <!--div class="field">
    <%= f.label :frequent_donor %><br />
    <%= f.text_field :frequent_donor %>
  </div-->
  <br/>
  <div class="actions text-center">
    <%= f.submit 'Enviar',  :class=>"btn btn-primary " %><br/><br/>
  </div>
  </div>
<% end %>

app/views/members/new.html.erb
<style>
 body {
    padding-top: 120px;
    padding-bottom: 40px;
    background-color: #eee;
  
  }

  .fullscreen_bg {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-size: cover;
    background-position: 50% 50%;
    background-image: url('assets/background2.JPG');
    background-repeat:repeat;
  }

</style>
<div id="fullscreen_bg" class="fullscreen_bg"/>
<body >
	<div class="col-md-6 col-md-offset-3 wells">
		<h1 class="text-center">Nuevo Voluntario</h1>

		<%= render 'volunteer' %>

	</div>
</body>

app/views/members/new_member.html.erb
<style>
 body {
    padding-top: 120px;
    padding-bottom: 40px;
    background-color: #eee;
  
  }

  .fullscreen_bg {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-size: cover;
    background-position: 50% 50%;
    background-image: url('assets/background2.JPG');
    background-repeat:repeat;
  }

</style>
<div id="fullscreen_bg" class="fullscreen_bg"/>
<body >
	<div class="col-md-6 col-md-offset-3 wells">
		<h1 class="text-center">Nuevo miembro</h1>

		<%= render 'form_member' %>

	</div>
</body>

app/views/members/padrinos.html.erb
<style type="text/css">
.btn-radio {
  width: 100%;
}
.img-radio {
  opacity: 0.3;
  margin-bottom: 5px;
}

.space-20 {
    margin-top: 20px;
}
</style>
<script type="text/javascript">
$(function () {
    $('.btn-radio').click(function(e) {

      if( $(this).hasClass("active") ){
      
      $(this).removeClass('active')
        .siblings('input').prop('checked',false)
            .siblings('.img-radio').css('opacity','0.3');
          }
          else {
          	$(".btn-radio").removeClass('active');
          	$('input').prop('checked',false)
          	$('.img-radio').css('opacity','0.3');

      		$(this).addClass('active')
            .siblings('input').prop('checked',true)
        .siblings('.img-radio').css('opacity','1');

      }
    });
});
</script>
<h1 class="text-center">¡APADRINA A UN PELUDO!</h1>
<div class="text-center">
<h2> Por $30.000 mensuales podrás apadrinar a un perrito del refugio</h2>
<label> Te recomendamos programar una transferencia mensual a través de tu banco para que tu peludo siempre cuente con tu aporte</label>
</div>
<div class="well col-md-4 col-md-offset-4">
	<div class="row">
	<div class="col-md-3">Banco: </div><div class="col-md-6"> Banco estado </div><div class="col-md-3"></div>
	</div>
	<div class="row">
	<div class="col-md-3">Tipo cuenta: </div><div class="col-md-6"> Rut/Vista </div><div class="col-md-3"></div>
	</div>
	<div class="row">
	<div class="col-md-3">Número: </div><div class="col-md-6"> 15380940 </div><div class="col-md-3"></div>
	</div>
	<div class="row">
	<div class="col-md-3">Rut: </div><div class="col-md-6"> 15.380.940-2 </div><div class="col-md-3"></div>
	</div>
	<div class="row">
	<div class="col-md-3">Nombre: </div><div class="col-md-6"> Michelle Leon </div><div class="col-md-3"></div>
	</div>
	<div class="row">
	<div class="col-md-3">Mail: </div><div class="col-md-6"> refugioesperanzapd@gmail.com </div><div class="col-md-3"></div>
</div>
</div>
<% if @notice %>
	<div class="col-md-6 col-md-offset-3">
		<font color="red">ATENCION: <%= @notice %></font>
	</div>
<% end %>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= form_tag :controller => "members", :action => "create_padrino", :class=>"form-horizontal well", :id => 'form' do |f| %>
            <div class="field">
              <%= label_tag "Ingresa tu e-mail de contacto" %><br />
              <%= text_field_tag "member[email]", "", :class=>"form-control required", :required => true, :type => "email" %>
            </div>
            <div class="row text-center">
              <h2 class=" col-sm-12">Selecciona al perrito que quieres apadrinar </h2>
          </div>
            <div class="row">
              <% @dogs.each do |dog| %>           
                <div class="col-xs-2 text-center">
                  <%= image_tag dog.photo1.url(:thumb), :class=>"img-responsive img-radio", :alt => dog.name, :style=> "height:100px;width:100px;"%>
                    <button type="button" class="btn btn-primary btn-radio "> <%= dog.name %></button>
                    <input type="checkbox" id="dog" name="dog" class="hidden" value="<%= dog.id %>">
                </div>
              <% end %>
            </div>
            <div class="actions text-center"><br/>
			    <%= submit_tag '¡Apadrinar!', :class =>  "btn btn-success"%>
			</div>
          <%end%>
        </div>
    </div>
</div>

app/views/members/thank_you.html.erb
<style>
 body {
    padding-top: 120px;
    padding-bottom: 40px;
    background-color: #eee;
  
  }

  .fullscreen_bg {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-size: cover;
    background-position: 50% 50%;
    background-image: url('assets/background3.JPG');
    background-repeat:repeat;
  }

</style>
<div id="fullscreen_bg" class="fullscreen_bg"/>
<body>
	<div class="col-md-offset-3 col-md-6 text-center wells">
		<h1><%= @notice %></h1>
		<h2>¡Nos vemos!</h2>
		<br/>
	</div>


</body>

app/views/members/volunteer.html.erb
<style>
 body {
    padding-top: 120px;
    padding-bottom: 40px;
    background-color: #eee;
  
  }

  .fullscreen_bg {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-size: cover;
    background-position: 50% 50%;
    background-image: url('assets/background.JPG');
    background-repeat:repeat;
  }

</style>

<div id="fullscreen_bg" class="fullscreen_bg"/>

<div class="col-md-6 col-md-offset-3 text-center wells">
	<!--div class="text-center">
	<img src="https://scontent-mia.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/11042979_1558284331086707_7916111296664081739_n.jpg?oh=ac81325b68f9b3ca2e31829c4386e226&oe=559F442E" width="450"/>
</div-->

<h1>Inscríbete para el Operativo</h1>

<%= form_tag check_path, :id => "form" , :method => :get  do%>

  <div class="field col-md-8 col-md-offset-2 form-group required">
    <%= label_tag "(si ya tenemos tus datos no necesitarás ingresar nada más)" %><br />
    <%= text_field_tag :email, "", :placeholder => "Ingresa tu e-mail", :value => params[:email], :type => "email", :class=> "form-control required" %>
  </div>
 <div class="field col-md-8 col-md-offset-2 form-group">
    <%= check_box_tag :car%> <%= label_tag "Cuentas con un auto para este operativo" %>
  </div>
 <div class="actions">
    <%= submit_tag 'Quiero ir al operativo este domingo ' + DateTime.now.end_of_week.strftime("%d / %m / %Y"), :class => "btn btn-primary" %>
  </div>
  <br/>
<% end %>
</div>